### ISSUE TITLE
Feature Request, Add expiration date and others

### ISSUE THREAD

**Issue by dddns** [jannispinter/indicatetls#1]
Howdy,
If possible, the address could add more info, like the date when the cert was issued and expires.

Thanks in advanced,

**Comment by jannispinter** [comment]
The mid-term goal is to build something like [SSleuth](https://github.com/sibiantony/ssleuth), which will also display all the important information about the certificate (DN, not before, not after, SAN and other extensions, key usages, constraints).

**Comment by dddns** [comment]
Thank you.
For me, the top information is the not before, not after.
Thanks for your work,

**Comment by 3hhh** [comment]
Other interesting data:

- cipher suite
- fingerprint

**Comment by jannispinter** [comment]
Fixed by 696003e

**Comment by dddns** [comment]
Hi again, should have posted here.
Thanks a lot for the expiration data implementation, 
Now i can know the date of my websites with just one click, and it also has now some extra and interesting info.

Thanks many.

**Comment by 3hhh** [comment]
Yes, thanks a lot from me as well!
