### ISSUE TITLE
Yellow alert versus legibility

### ISSUE THREAD

**Issue by grahamperrin** [jannispinter/indicatetls#18]
Suggestion: 

- where the yellow alert appears with text, don't make the text illegible. 

Instead, maybe have the yellow alert over the relevant colour (e.g. green here at GitHub) – without the text.

**Comment by jannispinter** [comment]
Thank you! I don't fully understand what you mean, could you elaborate a bit?

Do you mean the yellow triangle in the address bar:
![grafik](https://user-images.githubusercontent.com/1999743/73124973-dee42680-3fa1-11ea-81ed-92e45e0d7416.png)

Or do you mean the (yellow) text within the main panel:
![grafik](https://user-images.githubusercontent.com/1999743/73125032-9aa55600-3fa2-11ea-8304-7a5310363643.png)

**Comment by Madis0** [comment]
I think they mean the address bar icon - as the 3 is partly covered, it is not as clear if it is 3 or 2.

**Comment by grahamperrin** [comment]
> Do you mean the yellow triangle in the address bar:

Yep. The obscured text is jarring; a minor annoyance. 

Better for the page action to have no text, if the yellow alert makes the text illegible. 

(The panel is fine.)

**Comment by Madis0** [comment]
Instead of the padlock, perhaps make the background yellow?
