### ISSUE TITLE
Indicate if algorithm used has perfect forward secrecy or not

### ISSUE THREAD

**Issue by Aaron-P** [jannispinter/indicatetls#2]
It would be nice if the icon would indicate that the algorithm being used on the main or other domains doesn't provide perfect forward secrecy, that is a non-ECDHE or DHE algorithm.

**Comment by jannispinter** [comment]
The mid-term goal is to build something like [SSLeuth](https://github.com/sibiantony/ssleuth), which will display usage of PFS suites. I am considering to change the icon to display a score from 0 (worst) to 10 (best).

**Comment by jannispinter** [comment]
Fixed by 696003e
