### ISSUE TITLE
Clarify "connected to"

### ISSUE THREAD

**Issue by Madis0** [jannispinter/indicatetls#20]
As of the SSLeuth redesign, the main tab bottom right corner has a text:

> **Connected to:** github.com [(SSL Labs)](https://www.ssllabs.com/ssltest/analyze.html?d=github.com)

That makes it seem like the extension needs to connect to SSL Labs every time to work or display the popup contents. As you are actually using the Firefox's API for this, I assume that is not the case.

Hence I suggest removing the "connected to" text altogether (the main view tab's name and contents are obvious enough) and wording it like

> [Run SSL Labs test](https://www.ssllabs.com/ssltest/analyze.html?d=github.com) to see more info

**Comment by jannispinter** [comment]
Thanks! Indeed, the wording is confusing here.
