### ISSUE TITLE
Data is missing or outdated on new tabs

### ISSUE THREAD

**Issue by Nothing4You** [jannispinter/indicatetls#22]
When I open a new tab, open a page and then check the extension I'm greeted with the following values:
<img width="1269" alt="Screen Shot 2020-01-27 at 07 35 24" src="https://user-images.githubusercontent.com/3694534/73154527-d55cda80-40d7-11ea-8c43-4472d224597d.png">

Sometimes this was fixed after a reload.
<img width="1240" alt="Screen Shot 2020-01-27 at 07 35 36" src="https://user-images.githubusercontent.com/3694534/73154526-d4c44400-40d7-11ea-9cb6-fe566cb581c2.png">

On another page I noticed it had an old certificate expiration date in there claiming that the cert expired nearly 90 days ago. Force-refreshing (cache override) seems to have fixed this issue.

Is this a firefox issue or an extension issue?

**Comment by jannispinter** [comment]
Thanks, this is odd and looks like a bug in Firefox itself. Do you see this behaviour for every page in a new tab or just for some?

The extension should display the same data you can see in the developer console under _network_ -> _security_ for the GET request to the main document.
![grafik](https://user-images.githubusercontent.com/1999743/73161952-f845b980-40ec-11ea-9dd2-ffb332a29878.png)

**Comment by Nothing4You** [comment]
i don't see it happening anymore currently so i'm closing this
