### ISSUE TITLE
No data is shown for a website with a single request

### ISSUE THREAD

**Issue by jannispinter** [jannispinter/indicatetls#23]
IndicateTLS does not show any data for websites that only require a single request (e.g. websites that don't fetch images, stylesheets or fonts). The page action shows the grey default icon (see screenshot below).

**Example:** [https://tls13.pinterjann.is](https://tls13.pinterjann.is) or when downloading a single file (e.g. a PDF file) from a web server.

![grafik](https://user-images.githubusercontent.com/1999743/73163279-efa2b280-40ef-11ea-981b-9ed3ffebcb59.png)

**Comment by rugk** [comment]
You likely (accidentially) limit the fetched requests to assets/subresources and exclude the top document. 😄

**Comment by jannispinter** [comment]
When refreshing the page repeatedly, you can see the green TLSv1.3 icon showing up for a fraction of a second before turning grey again. I think Firefox somehow resets the icon back to the default (which is the grey unknown icon) when the request for the main document has finished.
