### ISSUE TITLE
Popup doesn't load in private window due to getBackgroundPage()

### ISSUE THREAD

**Issue by Aaron-P** [jannispinter/indicatetls#3]
getBackgroundPage() always returns null in a private window (https://bugzilla.mozilla.org/show_bug.cgi?id=1329304), this prevents the popup from working.  Since it only seems to be used to load a couple of string maps the popup code could just use a local copy of the maps, or some other communication method if you don't want to maintain multiple copies.

**Comment by jannispinter** [comment]
Thanks for the hint. I have no issues with loading the popup in private windows. What platform and browser version are you using?

**Comment by Aaron-P** [comment]
Firefox 68.0.1 on both windows 8.1 and 10 don't show any contents in the popup for me when checked in a private window.

![image](https://user-images.githubusercontent.com/744119/62411793-53737500-b5be-11e9-8edb-9565d778f00c.png)

**Comment by jdreesen** [comment]
I can confirm that.

**Comment by jannispinter** [comment]
Thanks, I will look into it. I didn't notice it before because I set all my Firefox installs to always run in private mode, which apparently is less strict.
