### ISSUE TITLE
New default coloring

### ISSUE THREAD

**Issue by Madis0** [jannispinter/indicatetls#32]
As TLS 1.0 and 1.1 are getting disabled [(someday)](https://hacks.mozilla.org/2020/02/its-the-boot-for-tls-1-0-and-tls-1-1/), it is time to consider new colors to use to better highlight the differences.

- Ideally, perfect security must be transparent, therefore I suggest using the same gray color for 1.3 as Firefox itself uses for the padlock (black with opacity 0.6).

- Mixed protocols could perhaps use an icon crossed with a red line, similar to the [broken padlock](http://http.badssl.com)). 
A simple line should obstruct the number less than [the previous warning triangle](https://github.com/jannispinter/indicatetls/issues/18).

- Could 1.2 be yellow now? It's not specifically _bad_ until proven that a site uses insecure ciphers and it is still a recommended default. Maybe use a cross for [bad configurations](https://en.wikipedia.org/wiki/Transport_Layer_Security#Cipher) and 1.3 coloring for the rest? 

- 1.0 and 1.1 should be bright red while they still exist, [but is that enough?](https://github.com/jannispinter/indicatetls/issues/19#issuecomment-578430054)

- Wait, why is SSL 3 still in this extension?

- Unknown icon could be inverted, as it doesn't give much info anyway.

**Comment by jannispinter** [comment]
Ideally, perfect security must be transparent, therefore I suggest using the same gray color for 1.3 as Firefox itself uses for the padlock (black with opacity 0.6).

Agreed, I like your gray version. 

    Mixed protocols could perhaps use an icon crossed with a red line, similar to the broken padlock).
    A simple line should obstruct the number less than the previous warning triangle.

Agreed, a red line feels more "Firefox-like".

    Could 1.2 be yellow now? It's not specifically bad until proven that a site uses insecure ciphers and it is still a recommended default. Maybe use a cross for bad configurations and 1.3 coloring for the rest?

Agreed, TLSv1.2 should be yellow now to push TLSv1.3. 

    1.0 and 1.1 should be bright red while they still exist, but is that enough?

Yes, let's make them red, they should not be used any more.

    Wait, why is SSL 3 still in this extension?

SSLv3 is disabled by default, I'm not sure if support for it was entirely removed in Firefox (e.g. what happens if you set `security.tls.version.min` to `0`). We can remove it, if there is no way in Firefox to re-enable it.

    Unknown icon could be inverted, as it doesn't give much info anyway.

Agreed.

**Comment by Madis0** [comment]
> SSLv3 is disabled by default, I'm not sure if support for it was entirely removed in Firefox

Confirmed that it does not exist in latest Nightly by [SSLLabs](https://www.ssllabs.com/ssltest/viewMyClient.html), so unless you want to support old Pale Moon or something, you can remove this :grin: 

> Agreed, a red line feels more "Firefox-like".

Could you [revise and revert this commit](https://github.com/jannispinter/indicatetls/commit/0fb0483c8afc8d8e420815b9be6a0483db2a1951) then?

**Comment by jannispinter** [comment]
The TLSv1.3 icon looks odd when using the (official) dark theme. I think 60% transparency does not work so well here. The padlock actually has a different color in both themes, so removing the transparency and replacing it with a solid gray color does not work either.
![grafik](https://user-images.githubusercontent.com/1999743/77640345-835ef680-6f5a-11ea-94a0-f71f77b2aaec.png)
![grafik](https://user-images.githubusercontent.com/1999743/77640144-2bc08b00-6f5a-11ea-9a60-17ca361aa293.png)

I'm not sure yet what the best way would be to deal with it. Maybe we need to use different icons depending on the theme.

**Comment by Madis0** [comment]
Well, if we did a solid gray color, it could blend in too much depending on the theme (maybe even the official dark one). Perhaps a white border around would help?

**Comment by Madis0** [comment]
Actually, why does it matter? As long as the numbers themselves are readable, it doesn't matter if the background is. Because _deemphasis was the point._

**Comment by jannispinter** [comment]
Just fixed a few minor issues within the code to make it work better. I like the new icons a lot! 

I noticed that the padlock icon uses a red bar that is oriented from top right to bottom left. But the new icons use a red bar from top left to bottom right, should we swap the orientation to match with the padlock?
![grafik](https://user-images.githubusercontent.com/1999743/77740714-03956280-7014-11ea-95d7-5e019e0b293a.png)
![grafik](https://user-images.githubusercontent.com/1999743/77740846-3ccdd280-7014-11ea-8624-5a439019b55a.png)

We should also re-add some kind of explanatory text to make it clear why the icon has a red crossed bar. Maybe even just as a tooltip when hovering over the icon.

**Comment by Madis0** [comment]
> should we swap the orientation to match with the padlock?

Sure, that would make sense. You could even use the original cross by taking it from the SVG `chrome://browser/skin/connection-mixed-active-loaded.svg`.

> We should also re-add some kind of explanatory text to make it clear why the icon has a red crossed bar. Maybe even just as a tooltip when hovering over the icon.

I thought #19 is sufficient, but yes, you can add a tooltip.

**Comment by jannispinter** [comment]
> Sure, that would make sense. You could even use the original cross by taking it from the SVG chrome://browser/skin/connection-mixed-active-loaded.svg.

Just updated the icons.

> I thought #19 is sufficient, but yes, you can add a tooltip.

For some reason the triangle is not displayed in the current version, will investigate.

**Comment by jannispinter** [comment]
> For some reason the triangle is not displayed in the current version, will investigate.

Fixed it. Thank you @Madis0! :rocket: 

I will test it further and release it tonight.

**Comment by 532910** [comment]
> ![grafik](https://user-images.githubusercontent.com/1999743/77640345-835ef680-6f5a-11ea-94a0-f71f77b2aaec.png)
> ![grafik](https://user-images.githubusercontent.com/1999743/77640144-2bc08b00-6f5a-11ea-9a60-17ca361aa293.png)

While white theme looks fine, the black color on the dark one confuses.

> I'm not sure yet what the best way would be to deal with it. Maybe we need to use different icons depending on the theme.

It seems so.

**Comment by ArchangeGabriel** [comment]
Indeed, I think matching other icons colors would be nicer. So lighter background and dark text.
