### ISSUE TITLE
TLS 1.3 color

### ISSUE THREAD

**Issue by lxwndr** [jannispinter/indicatetls#38]
Can you adopt another color for greater security (1.3)? For example, the color green.

On dark Firefox themes, the extension is barely visible.

![Screen Capture_select-area_20200427193241](https://user-images.githubusercontent.com/45263160/80427339-e3c8b700-88bd-11ea-84b4-b6555e0588f8.png)

**Comment by jannispinter** [comment]
We had this before, but changed it in #32 for TLSv1.3 to gray so that it matches the padlock's color (in the default light theme). Unfortunately, in dark themes, the indicator icon is black rather than gray.

**Comment by lxwndr** [comment]
With the black/gray color, I don't have the impression of security. It is traditional to display the safest things in green.

~~HTTP -> Violet (no security)~~
TLS 1.0 -> Red (low security)
TLS 1.2 -> Yellow (medium security)
TLS 1.3 -> Green (high security)

**Comment by d7415** [comment]
As discussed in #32, many tools are going for the new policy of making poor security obvious, good security transparent. You can already see this in browsers - the icon for an HTTP site is far more obvious than that for HTTPS for example.

**Comment by lxwndr** [comment]
> As discussed in #32, many tools are going for the new policy of making poor security obvious, good security transparent. You can already see this in browsers - the icon for an HTTP site is far more obvious than that for HTTPS for example.

That information makes sense. I ask that you ignore the HTTP part @jannispinter.

**Comment by 532910** [comment]
Black color looks like something is wrong, it should be light grays the same as https lock sign
Moreover screenshots ([in README.md](https://camo.githubusercontent.com/91c46b9520a1e6f87de5552b1e3b5423321ce067/68747470733a2f2f6164646f6e732e63646e2e6d6f7a696c6c612e6e65742f757365722d6d656469612f70726576696577732f66756c6c2f3233312f3233313431302e706e67) and [on AMO](https://addons.cdn.mozilla.net/user-media/previews/thumbs/231/231410.png?modified=1579990423)) MUST be updated!

**Comment by jannispinter** [comment]
>  Moreover screenshots (in README.md and on AMO) MUST be updated!

I will update the screenshots once we have a working solution for dark themes. I agree that we should find a way to match the padlock icon regardless of the current theme.

**Comment by jannispinter** [comment]
It looks like we can get the color using `browser.theme.getCurrent().colors.icon` with something like this:

```
function getStyle(themeInfo) 
{
  if (themeInfo.colors) 
  {
    console.log("icon color: " +  themeInfo.colors.icon);
  }
}

async function getCurrentThemeInfo() 
{
  var themeInfo = await browser.theme.getCurrent();
  getStyle(themeInfo);
}

getCurrentThemeInfo();
```
We could try to generate an SVG on the fly with the color obtained from the theme. But for now, we could simply detect the default dark and white themes and display the corresponding version of the icon.

**Comment by lxwndr** [comment]
> Black color looks like something is wrong, it should be light grays the same as https lock sign
> Moreover screenshots ([in README.md](https://camo.githubusercontent.com/91c46b9520a1e6f87de5552b1e3b5423321ce067/68747470733a2f2f6164646f6e732e63646e2e6d6f7a696c6c612e6e65742f757365722d6d656469612f70726576696577732f66756c6c2f3233312f3233313431302e706e67) and [on AMO](https://addons.cdn.mozilla.net/user-media/previews/thumbs/231/231410.png?modified=1579990423)) MUST be updated!

As this old capture shows, the color of the TLS 1.3 icon is green; as I suggested earlier.

Every higher level of security is represented by the color green (like HTTPS in browsers). Using the black / gray color (regardless of the themes) does not make sense to me.

![Screen Capture_select-area_20200502162017](https://user-images.githubusercontent.com/45263160/80875883-47256100-8c91-11ea-9165-5861de6f7686.png)

Note: 1 - I suggest increasing the size of the icon a little or showing only the colored numbers, removing the square (see how it looks better, they are just ideas). 2 - Try to adopt the transparent color of the numbers inside the square; in the dark theme of Firefox, the background color of the search bar should look better instead of white.

**Comment by d7415** [comment]
> As this old capture shows, the color of the TLS 1.3 icon is green; as I suggested earlier.

Again, #32.

**Comment by jannispinter** [comment]
> Every higher level of security is represented by the color green (like HTTPS in browsers). Using the black / gray color (regardless of the themes) does not make sense to me.

We changed it in #32 to adapt to the current behaviour of Firefox (the padlock changed from green to gray some releases ago). The general idea is to no longer show "positive marks" when something is good, but only show "negative marks" when something is not good/perfect. This is because the web is transitioning to a secure by default state, where HTTPS is the norm. When a website uses TLSv1.3, it uses perfectly secure transport security (which is - or should be - the new norm) so we only show a quiet, gray icon.

> Note: 1 - I suggest increasing the size of the icon a little or showing only the colored numbers, removing the square (see how it looks better, they are just ideas). 2 - Try to adopt the transparent color of the numbers inside the square; in the dark theme of Firefox, the background color of the search bar should look better instead of white.

Thanks for those two ideas, I will try to address this in the next releases to make it more accessible and legible.

> But for now, we could simply detect the default dark and white themes and display the corresponding version of the icon.

Good news, I got this working on my local machine here, and I like it so far. I'll test it further and ship it tonight together with everything currently in master.

**Comment by 532910** [comment]
removing the square could be nice

**Comment by lxwndr** [comment]
> We changed it in #32 to adapt to the current behaviour of Firefox (the padlock changed from green to gray some releases ago). The general idea is to no longer show "positive marks" when something is good, but only show "negative marks" when something is not good/perfect. This is because the web is transitioning to a secure by default state, where HTTPS is the norm. When a website uses TLSv1.3, it uses perfectly secure transport security (which is - or should be - the new norm) so we only show a quiet, gray icon.

According to the developer's explanation and the availability of the new update, with a new color for the dark theme, I am closing this topic.

![Screen Capture_select-area_20200502210814](https://user-images.githubusercontent.com/45263160/80895257-21ac4d80-8cb9-11ea-85cc-bc25e1a310a5.png)

**Comment by 532910** [comment]
Why it uses own colors?
![image](https://user-images.githubusercontent.com/14617699/80896464-2e4f9680-8cf7-11ea-9d49-62b7b07a6d20.png)
The lock (and the fav star) color is `#b1b1b3` so the square also should be `#b1b1b3`.
The background around the lock is `#474749` so the text color also should be `#474749`

https://contrastchecker.com/?c=474749&b=b1b1b3

**Comment by 532910** [comment]
Any update?
