### ISSUE TITLE
No HTTPS

### ISSUE THREAD

**Issue by lxwndr** [jannispinter/indicatetls#39]
When accessing an HTTPS address, display an open lock icon.

It can take a dark purple or gray color.

![istockphoto-898656072-1024x1024](https://user-images.githubusercontent.com/45263160/80428128-8897c400-88bf-11ea-9981-b382c3fdae27.jpg)

**Comment by jannispinter** [comment]
We can easily do this, but what should be displayed when a user clicks on the open padlock icon? Without TLS, there is not much we can display to the user that is meaningful for TLS.

**Comment by lxwndr** [comment]
> When accessing an HTTPS address, display an open lock icon.
HTTP *

You can display the message:
"This connection is not secure and can be intercepted. Always prefer secure websites (https)".

**Comment by jannispinter** [comment]
Thanks for the suggestion, but I believe this is beyond the scope of this extension and adds no value to the current behaviour of Firefox. Firefox already displays a padlock with a crossed, red bar on HTTP-only pages (e.g. on [httpforever.com](http://httpforever.com)) and provides explanatory text when clicked.

I am closing this issue therefore.
