### ISSUE TITLE
Extension leaks http basic auth credentials

### ISSUE THREAD

**Issue by Nothing4You** [jannispinter/indicatetls#4]
Hi,

when opening the extension on a page using http basic auth it displays user:pass@host rather than just host. This is also used for the SSL Labs test, the Run test link links to https://www.ssllabs.com/ssltest/analyze.html?d=user.pass@host

**Comment by jannispinter** [comment]
Thanks for pointing this out, this is really bad.

Do you have any recommendation how to properly fix this? I could simply strip everything before (and including) the '@' character. However, there might be even more things we should sanitize in the domain part.

**Comment by Nothing4You** [comment]
If you parse it as an URL in JS you could use the host attribute: https://developer.mozilla.org/en-US/docs/Web/API/URL

**Comment by Nothing4You** [comment]
I guess that could replace [getDomain()](https://github.com/jannispinter/indicatetls/blob/master/background.js#L43)

**Comment by Nothing4You** [comment]
While looking at that I also don't think it's a good idea to hide the www. prefix as that might be a different webserver with different content.

**Comment by Nothing4You** [comment]
I just verified that this only happens when you visit the link by opening the link https://user:pass@host in your browser directly.
If you visit https://host and then login with your credentials they are not leaked.
