### ISSUE TITLE
add a tip about cache invalidation

### ISSUE THREAD

**Issue by jonathanlermitage** [jannispinter/indicatetls#44]
This addon may display a badge showing "?" until you force refresh (ctrl+F5) or clear Firefox cache.  
I think you could add a tip about cache invalidation when addon can't retrieve TLS info. Some inexperienced users may face this issue.

Thx for this excellent addon! :-)

**Comment by ashucg** [comment]
@jonathanlermitage, something like this?

![image](https://user-images.githubusercontent.com/11291284/87299160-2303bd00-c529-11ea-853e-47dd0a71855f.png)

**Comment by jonathanlermitage** [comment]
Perfect 👍
