### ISSUE TITLE
TLS v1.3 everywhere.

### ISSUE THREAD

**Issue by alberto-barbieri** [jannispinter/indicatetls#50]
I get TLS 1.3 everywhere, even on a site that don't have TLS v1.3
I'm testing this site : littlecaesars.com.tr
![1](https://user-images.githubusercontent.com/45793364/107495938-ff712580-6b90-11eb-997e-abbef8c2cff0.png)
![2](https://user-images.githubusercontent.com/45793364/107495954-04ce7000-6b91-11eb-98d7-89500871c6b5.png)

and this is the ssllab https://www.ssllabs.com/ssltest/analyze.html?d=littlecaesars.com.tr

I tried again with this https://cap5.gestour360.com/
and it say it use TLS 1.3
But this is the ssllab https://www.ssllabs.com/ssltest/analyze.html?d=cap5.gestour360.com

I even tried to run this extension in Private Mode, but I get the same results

**Comment by jannispinter** [comment]
Hi there, seems like you are using a proxy (PortSwigger, BurpSuite) that supports TLS 1.3. There is nothing we can do to detect the TLS version of the destination host, when Firefox only sees the handshake with the MITM proxy.

**Comment by alberto-barbieri** [comment]
> Hi there, seems like you are using a proxy (PortSwigger, BurpSuite) that supports TLS 1.3. There is nothing we can do to detect the TLS version of the destination host, when Firefox only sees the handshake with the MITM proxy.

U solved my problem. Didn't know I could not use a proxy. When I disable the proxy, just for checking the TLS/SSL version, it work fine. Ty :)
