### ISSUE TITLE
Indicate EncryptedClientHello

### ISSUE THREAD

**Issue by yoshimo** [jannispinter/indicatetls#52]
To see which Hosts support the upcoming ECH Standard, it would be great to have that info in the addon

**Comment by jannispinter** [comment]
We currently use the [SecurityInfo API](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/webRequest/SecurityInfo), but as far as I can see it does not tell us whether ECH is supported or not. 

I am not sure how we could see which hosts support ECH and which do not, as this would require us to send low level network requests from within the extension. Do you know of any other browser API we could call to check for ECH?

**Comment by yoshimo** [comment]
The whole thing is connected to https://bugzilla.mozilla.org/show_bug.cgi?id=1634793
but i need to dig deeper how the browser itself does it.

**Comment by ghost** [comment]
The info is now available here: 
[https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/webRequest/SecurityInfo#usedech](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/webRequest/SecurityInfo#usedech)

**Comment by jannispinter** [comment]
Thank you @oxygen50 for letting me know, this should be easy to implement. I will take a look at it this weekend. Maybe we can ship a new version of IndicateTLS soon, it hasn't been updated in a while.

**Comment by ghost** [comment]
Would be nice to have a update! Thanks a lot. I also had a small char error with Cloudflare certs. See here: [https://github.com/jannispinter/indicatetls/issues/57](https://github.com/jannispinter/indicatetls/issues/57 )
Other than that it seems to be working fine

**Comment by jannispinter** [comment]
Update to v0.3.1 was just submitted to Mozilla and is already available for download. Looks like this currently:
![image](https://github.com/jannispinter/indicatetls/assets/1999743/919b9c01-8668-4020-8f7d-b89a8ec57990)
