### ISSUE TITLE
Small char error with Cloudflare certs

### ISSUE THREAD

**Issue by ghost** [jannispinter/indicatetls#57]
Hello,

when looking at cloudflare certs there seems to be a " error from the parsing. See screenshot 👍 

![grafik](https://github.com/jannispinter/indicatetls/assets/95914791/c30b5f36-8060-4d9d-a7d9-c1d5621dc6fd)

**Comment by jannispinter** [comment]
I have applied a temporary fix for this in v0.3.1, but I'll have to rewrite the issuer parsing code to fix it completely.
